//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom13_UngDungBanCoffeeOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public int st_id { get; set; }
        public string st_name { get; set; }
        public string st_username { get; set; }
        public string st_password { get; set; }
        public Nullable<System.DateTime> st_dob { get; set; }
        public string st_gender { get; set; }
        public string st_address { get; set; }
        public string st_email { get; set; }
        public string st_phone { get; set; }
        public Nullable<int> fac_id { get; set; }
    }
}
